language: php

sudo: false

services:
  - docker

matrix:
  fast_finish: true

install:
  - ./setup.sh
  - docker-compose exec api php bin/console doctrine:fixtures:load -n

script:
  #- docker-compose exec api php bin/phpunit
  - docker-compose run testing

deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    tags: false
