version: '3'
services:
  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080
    links:
      - db:db

  web:
    restart: always
    build:
      context: front/.
    ports:
      - 8005:8005
    volumes:
      - ./front/:/usr/src/app/

  api:
    build:
      context: api/.
    restart: always
    env_file:
      - ./api/.env
    links:
      - db:db
    depends_on:
      - db

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./api/public/:/usr/src/app
      - ./docker_config/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80
    links:
      - api
