version: '3'
services:
  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080
    links:
      - db:db

  web:
    restart: always
    build:
      context: front/.
    ports:
      - ${FRONT_PORT}:8005
    volumes:
      - ./front/:/usr/src/app/
    depends_on:
      - api

  api:
    build:
      context: api/.
    restart: always
    links:
      - db:db
    volumes:
      - ./api/:/usr/src/app/

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./api/public/:/usr/src/app
      - ./docker_config/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80
    links:
      - api

  testing:
    build:
      context: e2e-tests/.
    restart: always
    volumes:
      - ./e2e-tests/tests/:/integration-tests/
      - ./e2e-tests/screenshots/:/screenshots/
    command: 'wait-for-it.sh web:8005 -- mocha --timeout 30000 --recursive /integration-tests'
    depends_on:
      - web